#### try catch

#### example : 1, throwing integer

        try {
            std::cout << "Throwing an integer exception...\n";
            throw 42;
        } catch (int i) {
            std::cout << " the integer exception was caught, with value: " << i << '\n';
        }

        output : 
        Throwing an integer exception...
        the integer exception was caught, with value: 42

#### example : 2, throwing string, catch string as character
    
        try {        
            throw "some exception";
        } catch (const char* msg) {
            std::cout << msg << '\n';
        }
    
#### example 3 :   catch-all block catches all exception , catch(...) : postition : at the end
        try{
            throw 10;        
        }catch(char *excp){
            std::cout << "caught" << std::endl;
        }catch(...){
            std::cout << "default" << std::endl;
        }
        
        
#### rethrowing exception        
      
        try{
            try{
                throw "some exception";        
            }catch(const char* ch){
                std::cout << ch << std::endl;
                throw;//rethrowing same exception
            }
        }catch(const char* ch){
            std::cout << "receiving rethowing : " << ch << std::endl;
        }



####
