> example 

        #include <iostream>
        int main() {
            try{
                throw std::exception();        
            }catch(std::exception e){
                std::cout << e.what() << std::endl;     
            }
            return 0;
        }

std::exception is the base class for the following important exceptions:

■ bad_alloc —Thrown when a request for memory using new fails


■ bad_cast —Thrown by dynamic_cast when you try to cast a wrong type
(a type that has no inheritance relation)


■ ios_base::failure —Thrown by the functions and methods in the iostream
library


--- 

#### bad_alloc : example : size of array

          #include <iostream>
          int main() {
              try{
                  std::cout << "enter size of array" << std::endl;
                  int size;
                  std::cin >> size; 
                  int* array = new int[size];        
              }catch(std::bad_alloc e){
                  std::cout << "invalid size of array : " << e.what() << std::endl;     
              }
              return 0;
          }

          output : 
          
          enter size of array
          -1
          invalid size of array : std::bad_alloc

---


#### bad_cast

        #include <iostream>
        class Base {virtual void member(){}};
        class Derived : public Base {};
        int main(){
            try{
                Base b;
                Derived& rd = dynamic_cast<Derived&>(b);
                
                //Derived d;
                //Base* pb;
                //pb = dynamic_cast<Base*>(&d); 
            }catch(std::bad_cast& bc){
                std::cerr << "bad_cast caught: " << bc.what() << std::endl;
            }
            return 0;
        }



---
#### length error : vector(dynamic in size ,but) size cannot be increase more than max_size

        // length_error example
        #include <iostream>       // std::cerr
        #include <stdexcept>      // std::length_error
        #include <vector>         // std::vector

        int main (void) {
          try {
              //vectors are dynamic in size, but has a limited max_size
            // vector throws a length_error if resized above max_size
            std::vector<int> myvector;
            myvector.resize(myvector.max_size()+1);
          }
          catch (const std::length_error& le) {
                  std::cerr << "Length error: " << le.what() << '\n';
          }
          return 0;
        }

        output : 
        g++ filename.cpp
        ./a.out
        Length error: vector::_M_default_append
        
